export const UNIT_CODE_OPTIONS = [
  { code: "H87", label: "Piece" },
  { code: "C62", label: "One" },
  { code: "NAR", label: "Number of articles" },
  { code: "SET", label: "Set" },
  { code: "PR", label: "Pair" },
  { code: "XBX", label: "Box" },
  { code: "XPK", label: "Package" },
  { code: "XCT", label: "Carton" },
  { code: "KGM", label: "Kilogram" },
  { code: "GRM", label: "Gram" },
  { code: "TNE", label: "Tonne" },
  { code: "LTR", label: "Litre" },
  { code: "MLT", label: "Millilitre" },
  { code: "MTR", label: "Metre" },
  { code: "CMT", label: "Centimetre" },
  { code: "MMT", label: "Millimetre" },
  { code: "KMT", label: "Kilometre" },
  { code: "MTK", label: "Square metre" },
  { code: "MTQ", label: "Cubic metre" },
  { code: "HUR", label: "Hour" },
  { code: "DAY", label: "Day" },
  { code: "MON", label: "Month" },
  { code: "ANN", label: "Year" },
  { code: "KWH", label: "Kilowatt hour" },
  { code: "E48", label: "Service unit" },
] as const;

export const UNIT_CODES = UNIT_CODE_OPTIONS.map((unit) => unit.code) as [string, ...string[]];
